language: go
go:
- "1.13"

cache:
  directories:
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod

script:
- go mod download
- make build
- ./go.test.sh
  
after_success:
- bash <(curl -s https://codecov.io/bash)
